In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00206") # marriage rate
df.head()

,freq,indic_de,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,GNUPRT,AD,NaN,NaN,NaN,NaN,NaN,3.9,NaN,NaN,NaN,NaN,NaN,NaN
1,A,GNUPRT,AL,8.2,8.2,8.7,7.8,7.9,8.1,7.9,6.2,7.0,6.8,NaN,6.8
2,A,GNUPRT,AM,NaN,NaN,5.9,5.4,5.1,5.0,5.3,NaN,NaN,NaN,5.5,NaN
3,A,GNUPRT,AT,4.3,4.4,5.1,5.1,5.1,5.3,5.2,4.4,NaN,NaN,5.0,5.0
4,A,GNUPRT,AZ,9.2,8.9,7.1,6.8,6.4,6.3,6.4,NaN,NaN,6.1,NaN,NaN

In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00014") # age at first marriage
df.head()

,freq,indic_de,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,FAGEMAR1,AM,NaN,NaN,26.8,NaN,26.7,26.7,NaN,NaN,NaN,NaN,NaN,NaN
1,A,FAGEMAR1,AT,30.7,30.9,31.2,31.3,31.5,31.7,32.0,NaN,NaN,NaN,32.7,NaN
2,A,FAGEMAR1,AZ,NaN,24.4,NaN,NaN,23.9,23.8,24.0,NaN,NaN,NaN,NaN,NaN
3,A,FAGEMAR1,BE,NaN,NaN,NaN,NaN,31.2,NaN,NaN,32.0,32.2,32.7,32.9,NaN
4,A,FAGEMAR1,BG,26.7,26.9,27.0,27.1,27.3,27.5,27.8,28.1,28.3,28.6,28.9,29.3

In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tessi180") # income quintiles
df.head()

,freq,age,sex,unit,geo\TIME_PERIOD,2005,2006,2007,2008,2009,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,A,TOTAL,F,RAT,AL,NaN,NaN,NaN,NaN,NaN,...,NaN,7.50,7.05,6.37,5.86,5.72,5.09,4.85,NaN,NaN
1,A,TOTAL,F,RAT,AT,3.80,3.72,3.80,4.16,4.11,...,3.98,4.35,4.01,4.14,4.04,4.04,4.17,4.19,4.27,NaN
2,A,TOTAL,F,RAT,BE,3.78,3.97,3.84,4.06,3.89,...,3.75,3.80,3.73,3.54,3.56,3.36,3.46,3.35,3.38,3.19
3,A,TOTAL,F,RAT,BG,NaN,5.09,6.95,6.48,5.96,...,7.43,8.00,7.41,7.75,7.87,7.54,7.20,6.23,6.56,6.71
4,A,TOTAL,F,RAT,CH,NaN,NaN,4.65,4.87,4.75,...,4.29,4.37,4.27,4.50,4.73,4.64,4.75,4.83,4.69,NaN

In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00216") # divorce rate
df.head()

,freq,indic_de,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,GDIVRT,AL,NaN,1.5,1.3,1.9,1.6,1.7,2.1,1.5,1.1,NaN,NaN,2.0
1,A,GDIVRT,AM,NaN,NaN,1.2,1.2,NaN,1.3,1.3,1.1,NaN,NaN,1.5,NaN
2,A,GDIVRT,AT,1.9,1.9,1.9,1.8,1.8,1.8,1.8,1.7,1.6,1.5,1.6,1.6
3,A,GDIVRT,AZ,1.2,1.3,1.3,1.3,1.5,1.5,1.7,1.4,NaN,1.6,NaN,NaN
4,A,GDIVRT,BE,2.2,2.2,2.2,2.1,2.0,2.0,2.0,1.8,1.9,1.7,1.7,NaN