In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00206") # marriage rate
df.head()

,freq,indic_de,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,GNUPRT,AD,NaN,NaN,NaN,NaN,NaN,3.9,NaN,NaN,NaN,NaN,NaN,NaN
1,A,GNUPRT,AL,8.2,8.2,8.7,7.8,7.9,8.1,7.9,6.2,7.0,6.8,NaN,6.8
2,A,GNUPRT,AM,NaN,NaN,5.9,5.4,5.1,5.0,5.3,NaN,NaN,NaN,5.5,NaN
3,A,GNUPRT,AT,4.3,4.4,5.1,5.1,5.1,5.3,5.2,4.4,NaN,NaN,5.0,5.0
4,A,GNUPRT,AZ,9.2,8.9,7.1,6.8,6.4,6.3,6.4,NaN,NaN,6.1,NaN,NaN

In [19]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00014") # age at first marriage
df = df.sort_values(["geo\\TIME_PERIOD"])
df['indic_de'].unique()

<ArrowStringArray>
['FAGEMAR1', 'MAGEMAR1']
Length: 2, dtype: str

In [12]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("lfsa_ewhan2") # income quintiles
df.head()

,freq,nace_r2,wstatus,worktime,age,sex,unit,geo\TIME_PERIOD,2008,2009,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,A,CFAM,FT,Y15-24,F,HR,AT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,A,CFAM,FT,Y15-24,F,HR,BA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,A,CFAM,FT,Y15-24,F,HR,BE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,A,CFAM,FT,Y15-24,F,HR,BG,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,A,CFAM,FT,Y15-24,F,HR,CH,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import eurostat
import pandas as pd
df = eurostat.get_data_df("tps00216") # divorce rate
df.head()

,freq,indic_de,geo\TIME_PERIOD,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,GDIVRT,AL,NaN,1.5,1.3,1.9,1.6,1.7,2.1,1.5,1.1,NaN,NaN,2.0
1,A,GDIVRT,AM,NaN,NaN,1.2,1.2,NaN,1.3,1.3,1.1,NaN,NaN,1.5,NaN
2,A,GDIVRT,AT,1.9,1.9,1.9,1.8,1.8,1.8,1.8,1.7,1.6,1.5,1.6,1.6
3,A,GDIVRT,AZ,1.2,1.3,1.3,1.3,1.5,1.5,1.7,1.4,NaN,1.6,NaN,NaN
4,A,GDIVRT,BE,2.2,2.2,2.2,2.1,2.0,2.0,2.0,1.8,1.9,1.7,1.7,NaN

In [14]:
# Testing if bruin did write correctly to duckdb
import duckdb

with duckdb.connect(database='./data/duckdb.db') as conn:
    # print(conn.execute("SELECT * FROM information_schema.schemata").df())
    for table in ["load.divorce_rate", "load.age_at_marriage", "load.gender_pay_gap","load.marriage_rate"]:
        print(f"\n--- {table} ---")
        display(conn.execute(f"SELECT * FROM {table} ORDER BY country, year LIMIT 10").df())
    print(conn.execute("SELECT * FROM staging.hours_worked ORDER BY country, year LIMIT 20 ").df())

--- load.divorce_rate ---

  country  year  divorce_rate
0      AL  2014           1.5
1      AL  2015           1.3
2      AL  2016           1.9
3      AL  2017           1.6
4      AL  2018           1.7
5      AL  2019           2.1
6      AL  2020           1.5
7      AL  2021           1.1
8      AL  2024           2.0
9      AM  2015           1.2

--- load.age_at_marriage ---

   indic_de country  year  age_at_marriage
0  FAGEMAR1      AM  2015             26.8
1  MAGEMAR1      AM  2015             30.8
2  FAGEMAR1      AM  2017             26.7
3  MAGEMAR1      AM  2017             31.0
4  FAGEMAR1      AM  2018             26.7
5  MAGEMAR1      AM  2018             31.0
6  FAGEMAR1      AT  2013             30.7
7  MAGEMAR1      AT  2013             33.3
8  FAGEMAR1      AT  2014             30.9
9  MAGEMAR1      AT  2014             33.6

--- load.gender_pay_gap ---

  country  year  gender_pay_gap
0      AL  2018             6.8
1      AT  2006            25.5
2      AT  2007            25.5
3      AT  2008            25.1
4      AT  2009            24.3
5      AT  2010            24.0
6      AT  2011            23.5
7      AT  2012            22.9
8      AT  2013            22.3
9      AT  2014            22.2

--- load.marriage_rate ---

  country  year  marriage_rate
0      AD  2018            3.9
1      AL  2013            8.2
2      AL  2014            8.2
3      AL  2015            8.7
4      AL  2016            7.8
5      AL  2017            7.9
6      AL  2018            8.1
7      AL  2019            7.9
8      AL  2020            6.2
9      AL  2021            7.0

Empty DataFrame
Columns: [country, year, hours_worked_m, hours_worked_f, hours_worked_delta]
Index: []

In [8]:

import eurostat
import pandas as pd
df = eurostat.get_data_df("lfsa_eegan2") # pay gap normal
df.head(50)

,freq,unit,sex,age,nace_r2,geo\TIME_PERIOD,2008,2009,2010,2011,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,THS_PER,F,Y15-19,A,AT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,THS_PER,F,Y15-19,A,BA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A,THS_PER,F,Y15-19,A,BE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,THS_PER,F,Y15-19,A,BG,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A,THS_PER,F,Y15-19,A,CH,NaN,NaN,2.2,2.7,...,2.2,1.5,1.6,2.0,NaN,NaN,NaN,NaN,NaN,NaN
5,A,THS_PER,F,Y15-19,A,CY,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,A,THS_PER,F,Y15-19,A,CZ,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,A,THS_PER,F,Y15-19,A,DE,5.8,NaN,5.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,A,THS_PER,F,Y15-19,A,DK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,A,THS_PER,F,Y15-19,A,EA21,23.7,19.9,17.0,17.0,...,16.1,15.1,16.3,15.1,19.1,NaN,24.5,21.1,21.2,20.2
10,A,THS_PER,F,Y15-19,A,EE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,A,THS_PER,F,Y15-19,A,EL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,A,THS_PER,F,Y15-19,A,ES,3.1,2.3,2.0,1.2,...,1.0,1.0,2.1,2.2,2.1,NaN,1.8,1.5,NaN,1.1
13,A,THS_PER,F,Y15-19,A,EU27_2020,26.5,22.8,20.0,19.8,...,19.4,18.0,18.3,18.6,21.3,NaN,26.4,24.8,24.5,23.4
14,A,THS_PER,F,Y15-19,A,FI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,A,THS_PER,F,Y15-19,A,FR,NaN,NaN,NaN,NaN,...,2.5,3.1,3.6,NaN,NaN,NaN,7.0,NaN,6.4,5.7
16,A,THS_PER,F,Y15-19,A,HR,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,A,THS_PER,F,Y15-19,A,HU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,A,THS_PER,F,Y15-19,A,IE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,A,THS_PER,F,Y15-19,A,IS,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,A,THS_PER,F,Y15-19,A,IT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,A,THS_PER,F,Y15-19,A,LT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,A,THS_PER,F,Y15-19,A,LU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,A,THS_PER,F,Y15-19,A,LV,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,A,THS_PER,F,Y15-19,A,MK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,A,THS_PER,F,Y15-19,A,MT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,A,THS_PER,F,Y15-19,A,NL,8.3,6.8,4.9,5.3,...,4.8,4.3,4.0,3.7,4.4,4.9,6.9,6.3,5.5,4.8
27,A,THS_PER,F,Y15-19,A,NO,1.4,NaN,1.0,1.0,...,1.2,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,A,THS_PER,F,Y15-19,A,PL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,A,THS_PER,F,Y15-19,A,PT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,A,THS_PER,F,Y15-19,A,RO,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,A,THS_PER,F,Y15-19,A,RS,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,A,THS_PER,F,Y15-19,A,SE,NaN,NaN,1.5,1.3,...,1.5,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,A,THS_PER,F,Y15-19,A,SI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,A,THS_PER,F,Y15-19,A,SK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,A,THS_PER,F,Y15-19,A,TR,NaN,33.5,33.6,31.6,...,38.7,36.4,36.7,25.2,32.9,29.4,35.2,33.7,30.0,30.4
36,A,THS_PER,F,Y15-19,A,UK,4.4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,A,THS_PER,F,Y15-19,B,AT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,A,THS_PER,F,Y15-19,B,BG,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,A,THS_PER,F,Y15-19,B,CZ,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,A,THS_PER,F,Y15-19,B,DE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,A,THS_PER,F,Y15-19,B,DK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,A,THS_PER,F,Y15-19,B,EA21,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,A,THS_PER,F,Y15-19,B,EL,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,A,THS_PER,F,Y15-19,B,EU27_2020,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,A,THS_PER,F,Y15-19,B,FI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,A,THS_PER,F,Y15-19,B,FR,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,A,THS_PER,F,Y15-19,B,HU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,A,THS_PER,F,Y15-19,B,IE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,A,THS_PER,F,Y15-19,B,IT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:

import eurostat
import pandas as pd
df = eurostat.get_data_df("earn_gr_gpgr2") # pay gap normal
df.head(50)

,freq,unit,nace_r2,geo\TIME_PERIOD,2007,2008,2009,2010,2011,2012,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,PC,B,AL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,34.9,NaN,NaN,NaN,NaN,NaN,NaN
1,A,PC,B,AT,NaN,NaN,NaN,18.3,NaN,NaN,...,13.7,14.4,10.9,7.9,7.8,10.9,9.6,14.3,12.8,14.2
2,A,PC,B,BE,-7.2,-8.8,-10.1,-13.4,-10.4,-7.1,...,-1.5,-2.1,-2.6,-3.1,-2.0,-1.0,-0.3,1.2,1.0,1.0
3,A,PC,B,BG,26.9,23.7,18.8,15.9,16.4,21.2,...,17.7,15.0,14.5,12.2,14.1,13.4,14.3,14.7,18.2,10.9
4,A,PC,B,CH,NaN,7.8,7.7,5.2,10.4,9.6,...,9.3,8.3,8.1,9.4,8.4,5.7,5.2,4.3,4.7,4.4
5,A,PC,B,CY,NaN,39.7,27.7,15.5,16.6,17.4,...,35.6,29.3,34.3,42.2,39.2,30.0,20.7,7.4,10.8,11.3
6,A,PC,B,CZ,NaN,24.8,22.2,22.6,22.8,21.2,...,16.3,14.5,16.4,14.6,15.9,13.0,11.0,9.3,11.4,10.3
7,A,PC,B,DE,5.1,6.8,10.5,12.3,9.8,7.0,...,1.4,2.4,6.4,7.1,9.3,7.7,7.8,2.1,-0.8,-0.4
8,A,PC,B,DK,NaN,12.5,16.1,18.6,14.3,12.8,...,17.2,20.6,21.1,17.4,18.4,18.5,15.0,13.3,14.3,21.4
9,A,PC,B,EE,NaN,37.2,36.5,36.0,34.0,37.0,...,32.7,36.8,30.9,29.6,27.1,26.4,15.9,14.5,18.2,16.8
10,A,PC,B,EL,NaN,NaN,NaN,34.0,NaN,NaN,...,NaN,NaN,NaN,5.3,NaN,NaN,NaN,9.5,7.0,9.2
11,A,PC,B,ES,13.3,13.0,12.5,12.2,14.4,15.0,...,-12.6,-4.7,-8.3,-16.1,-16.7,-17.3,-17.9,-18.5,-13.5,-13.5
12,A,PC,B,FI,NaN,15.6,20.3,16.3,7.4,10.6,...,13.8,15.8,18.3,14.0,7.4,8.3,6.4,-3.7,-0.1,-0.3
13,A,PC,B,FR,NaN,3.1,9.6,13.5,12.9,13.4,...,14.9,15.4,16.4,17.2,13.1,12.1,8.7,7.0,7.6,6.5
14,A,PC,B,HR,NaN,NaN,NaN,-4.1,NaN,NaN,...,NaN,3.8,0.8,4.0,4.7,6.3,7.2,9.0,11.4,11.7
15,A,PC,B,HU,NaN,4.5,2.3,-12.2,-18.2,-13.9,...,NaN,-22.3,5.1,16.8,4.6,1.7,1.2,9.5,21.0,19.4
16,A,PC,B,IE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.4,NaN,NaN,NaN,10.5,NaN,NaN
17,A,PC,B,IT,NaN,NaN,NaN,-15.2,NaN,NaN,...,NaN,NaN,NaN,2.0,1.4,-0.2,-1.6,-3.6,-5.1,-2.3
18,A,PC,B,LT,14.1,14.3,5.0,1.2,2.5,3.9,...,5.7,6.6,7.2,6.9,3.4,3.6,4.2,6.4,5.8,6.1
19,A,PC,B,LU,NaN,NaN,NaN,-4.2,NaN,NaN,...,11.7,11.4,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,A,PC,B,LV,NaN,NaN,NaN,12.5,NaN,17.8,...,18.2,28.6,30.6,12.0,15.4,19.0,12.4,7.5,4.2,8.3
21,A,PC,B,ME,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,A,PC,B,MK,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,A,PC,B,MT,NaN,15.4,24.3,26.8,26.4,8.9,...,-7.6,1.2,1.7,28.9,19.2,7.4,-1.5,-8.9,-5.1,-4.0
24,A,PC,B,NL,NaN,30.0,25.8,27.5,29.7,35.8,...,19.3,18.7,15.4,15.5,12.5,12.4,8.1,5.7,14.2,14.2
25,A,PC,B,NO,NaN,13.0,11.5,12.8,10.2,9.4,...,12.5,9.7,8.0,6.5,5.3,5.9,5.2,2.6,2.7,3.1
26,A,PC,B,PL,28.1,25.4,22.7,20.0,20.9,21.8,...,18.6,15.8,15.6,20.0,17.9,15.8,15.1,14.3,15.3,16.3
27,A,PC,B,PT,-4.6,-6.4,-8.9,-12.3,-15.3,-18.7,...,-17.6,-16.2,-8.9,-4.7,-12.5,-13.0,-10.8,-11.4,-9.4,-18.3
28,A,PC,B,RO,11.0,-4.9,4.1,-13.9,-11.2,-12.2,...,-10.7,-12.9,-7.6,-2.9,-13.2,-14.6,-8.1,-8.4,-16.6,-3.4
29,A,PC,B,RS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-5.9,NaN,NaN,NaN,NaN,NaN,NaN
30,A,PC,B,SE,NaN,7.0,8.7,5.5,5.3,8.1,...,5.3,6.1,8.7,8.4,3.5,4.1,5.2,5.6,2.6,2.3
31,A,PC,B,SI,15.1,17.6,17.3,16.5,16.5,17.0,...,14.8,13.6,12.9,14.6,17.2,17.1,15.7,14.6,17.1,14.0
32,A,PC,B,SK,NaN,-2.2,2.9,5.1,-10.3,-8.2,...,14.1,17.6,20.6,21.5,18.4,16.0,15.7,14.1,9.8,10.2
33,A,PC,B,TR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,A,PC,B,UK,-5.6,6.4,3.4,5.5,-12.1,-1.5,...,11.2,7.1,5.6,1.1,NaN,NaN,NaN,NaN,NaN,NaN
35,A,PC,B-N,AL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN
36,A,PC,B-N,AT,26.7,26.2,25.5,25.2,24.7,24.3,...,23.4,22.3,22.3,22.0,21.7,21.0,21.0,20.5,20.2,19.7
37,A,PC,B-N,BE,15.3,15.2,15.1,15.1,14.1,13.0,...,10.8,10.4,10.2,10.1,9.3,8.3,7.4,6.8,6.7,6.7
38,A,PC,B-N,BG,12.6,13.2,14.5,14.1,13.7,15.1,...,14.9,13.7,13.6,13.1,14.2,13.7,15.2,15.3,16.1,14.7
39,A,PC,B-N,CH,NaN,23.5,23.5,23.0,20.6,20.3,...,20.0,19.6,19.6,20.3,19.9,19.6,18.6,18.2,18.4,17.3
40,A,PC,B-N,CY,29.4,27.6,27.0,26.1,24.9,24.3,...,21.0,19.9,18.9,17.9,18.8,18.9,20.6,21.8,22.1,21.3
41,A,PC,B-N,CZ,24.5,21.1,21.0,16.1,16.1,15.5,...,16.1,15.9,16.4,15.0,16.9,16.6,18.0,20.8,12.1,12.1
42,A,PC,B-N,DE,26.0,26.0,26.0,25.7,25.8,26.0,...,25.1,24.4,23.9,23.4,22.5,21.6,20.9,20.4,19.9,19.1
43,A,PC,B-N,DK,16.7,16.2,16.8,17.9,18.3,17.5,...,15.4,16.1,15.3,14.4,14.2,13.9,13.8,13.1,13.4,13.7
44,A,PC,B-N,EE,30.5,28.3,27.7,28.5,27.3,29.7,...,27.0,25.7,26.4,24.3,23.1,22.9,22.1,23.2,23.0,22.6
45,A,PC,B-N,EL,20.5,21.9,NaN,19.7,NaN,NaN,...,NaN,NaN,NaN,17.5,NaN,NaN,NaN,15.6,15.5,15.0
46,A,PC,B-N,ES,22.8,21.3,22.7,22.4,23.6,23.9,...,19.9,19.9,18.2,16.9,15.3,15.2,14.7,15.1,13.6,13.6
47,A,PC,B-N,FI,19.4,19.0,19.8,19.4,18.1,18.3,...,17.0,17.3,16.2,16.1,15.9,16.6,16.0,15.0,16.3,16.0
48,A,PC,B-N,FR,16.8,17.0,15.6,15.6,14.2,13.8,...,13.1,13.5,14.1,14.6,14.1,13.7,13.3,13.0,12.2,11.7
49,A,PC,B-N,HR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11.1,12.5,12.8,12.9,12.7,12.4,10.8,11.4,11.3